# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Peter Knego
[package]
name = "uc2_service"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uc_protocol = { path = "../uc_protocol" }
uc2_log = { path = "../uc2_log" }
ultima-journal = { path = "../ultima_journal" }
serde = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
uc2_node = { path = "../uc2_node" }
uc2_net = { path = "../uc2_net" }
uc2_client = { path = "../uc2_client" }
tempfile = { workspace = true }
